name: ST-Sell
version: 1.0
main: stanic.stsell.Main
author: Stanic
softdepend:
  - WorldGuard
  - ActionBarAPI
  - MVdWPlaceholderAPI
  - PlaceholderAPI
  - JH_StackMobs
  - AutoPickup
commands:
  sell:
    aliases:
      - vender
  drops:
    aliases:
      - menudrops
      - dropsmenu
      - items